import { AlertTriangle, ArrowRight, Flag, RefreshCw, Rocket, Server, Target } from "lucide-react";
import { AdminButton, Panel, StatCard } from "@/components/admin";
import type { ProjectControlOverview, ShopLaunchView } from "@/lib/project-control/api";
import { displayPercent, describeAction, relativeTime } from "@/pages/admin/project-control-helpers";
import { EvidenceStateBadge } from "./evidence-state";

export function ProjectControlExecutiveSummary({ overview, shopLaunch, evidenceState, onOpenPackage, onRefresh, refreshing }: { overview: ProjectControlOverview; shopLaunch: ShopLaunchView; evidenceState: string; onOpenPackage: (key: string) => void; onRefresh: () => void; refreshing: boolean }) {
  const next = overview.nextActions.highestPriority ?? shopLaunch.nextActions.highestPriority;
  const phase = shopLaunch.nextMilestone;
  const blocker = shopLaunch.blockers[0];
  const pilot = shopLaunch.phases.find((item) => item.key === "pn-pilot");
  const pilotReady = Boolean(pilot && pilot.readiness.overall >= 100);
  return <section aria-labelledby="pc-executive-heading" className="pc-section"><div className="pc-section-heading"><div><h2 id="pc-executive-heading">Partner Shop launch</h2><p>Can we launch, and what is stopping us?</p></div><div className="pc-summary-actions"><EvidenceStateBadge state={evidenceState} testId="pc-evidence-freshness" /><AdminButton variant="gold" onClick={onRefresh} disabled={refreshing} aria-label="Refresh GitHub evidence"><RefreshCw size={15} aria-hidden="true" />{refreshing ? "Refreshing GitHub…" : "Refresh GitHub"}</AdminButton></div></div><div className="pc-summary-grid"><StatCard label="Overall readiness" value={displayPercent(overview.readiness.overall)} foot="Server-authoritative weighted readiness" icon={<Target size={15} />} testId="pc-overall-readiness" /><StatCard label="Current phase" value={phase?.name ?? "Unknown"} foot={phase ? "Next recorded milestone" : "No active phase was returned"} testId="pc-current-phase" /><StatCard label="Pilot readiness" value={pilotReady ? "Ready" : "Not ready"} foot={pilot ? `${displayPercent(pilot.readiness.overall)} · G7–G20 excluded` : "Pilot state unknown"} icon={<Rocket size={15} />} testId="pc-pilot-readiness" /><StatCard label="Highest blocker" value={blocker?.packageTitle ?? "No open blocker"} foot={blocker?.description ?? "No open blocker was returned"} icon={<AlertTriangle size={15} />} testId="pc-highest-blocker" /><StatCard label="Staging" value="See evidence" foot="Commit and reachability below" icon={<Server size={15} />} testId="pc-staging-status" /><StatCard label="Production" value="See evidence" foot="Never inferred from CI" icon={<Server size={15} />} testId="pc-production-status" /><StatCard label="Last evidence refresh" value={relativeTime(overview.generatedAt)} foot="Programme snapshot generated" icon={<Flag size={15} />} testId="pc-last-refresh" /><Panel className="pc-next-action" title="Do this next" sub="Highest-priority server recommendation">{next ? <><button type="button" className="pc-action-link" onClick={() => onOpenPackage(next.packageKey)} data-testid="pc-next-action"><strong>{next.headline}</strong><ArrowRight size={17} aria-hidden="true" /></button><p>{describeAction(next)}</p></> : <p>There is no recommended action yet. Evidence and programme state remain visible below.</p>}</Panel></div></section>;
}
