import { ChevronDown, ChevronRight, ExternalLink } from "lucide-react";
import { Badge, Panel } from "@/components/admin";
import type { ShopLaunchView } from "@/lib/project-control/api";
import { confidenceBadgeVariant, displayPercent, statusBadgeVariant, statusLabel } from "@/pages/admin/project-control-helpers";
import { EvidenceStateBadge } from "./evidence-state";
import { useState } from "react";

export function PartnerShopLaunchProgression({ view, onOpenPackage }: { view: ShopLaunchView; onOpenPackage: (key: string) => void }) {
  const [open, setOpen] = useState<string | null>(null);
  const launch = view.phases.filter((phase) => phase.key !== "pn-backlog").slice(0, 10);
  const backlog = view.phases.find((phase) => phase.key === "pn-backlog");
  return <section className="pc-section" aria-labelledby="pc-launch-heading"><Panel title="Partner Shop Launch" sub="The ten recorded launch gates; the permanent backlog is separate."><ol className="pc-launch-list" data-testid="pc-launch-gates">{launch.map((phase, index) => { const expanded = open === phase.key; const blockers = phase.packages.flatMap((pkg) => pkg.blockers.filter((blocker) => !blocker.resolvedAt)); return <li key={phase.key} className="pc-launch-gate"><button type="button" className="pc-gate-toggle" onClick={() => setOpen(expanded ? null : phase.key)} aria-expanded={expanded} aria-controls={`pc-gate-${phase.key}`}><span className="pc-gate-order">{index + 1}</span><span className="pc-gate-name">{phase.name}</span><Badge variant={phase.readiness.overall >= 100 ? "act" : "prog"}>{displayPercent(phase.readiness.overall)}</Badge><span className="pc-gate-meta">{blockers.length} blocker{blockers.length === 1 ? "" : "s"}</span><EvidenceStateBadge state={phase.packages.some((pkg) => pkg.assessment.confidence === "stale") ? "stale" : phase.packages.some((pkg) => pkg.assessment.confidence === "contradictory") ? "contradictory" : phase.packages.length ? "current" : "unknown"} />{expanded ? <ChevronDown aria-hidden="true" /> : <ChevronRight aria-hidden="true" />}</button>{expanded && <div id={`pc-gate-${phase.key}`} className="pc-gate-detail">{phase.packages.length === 0 ? <p>No package evidence has been recorded for this gate.</p> : phase.packages.map((pkg) => <div className="pc-gate-package" key={pkg.key}><span><strong>{pkg.title}</strong><small>{pkg.summary ?? "No summary recorded."}</small></span><Badge variant={statusBadgeVariant(pkg.assessment.effectiveStatus)}>{statusLabel(pkg.assessment.effectiveStatus)}</Badge><Badge variant={confidenceBadgeVariant(pkg.assessment.confidence)}>{pkg.assessment.confidence.replace(/_/g, " ")}</Badge><button type="button" onClick={() => onOpenPackage(pkg.key)} aria-label={`Open ${pkg.title}`}><ExternalLink size={15} /></button></div>)}</div>}</li>; })}</ol>{backlog && <div className="pc-backlog" data-testid="pc-permanent-backlog"><strong>Permanent backlog · G7–G20</strong><span>{backlog.description}</span><Badge variant="wait">Separate from pilot readiness</Badge></div>}</Panel></section>;
}
