export const VAULT_QUEST_COMPONENT = {
  schemaVersion: 1,
  id: "vault-quest",
  owner: "vault-quest-platform",
  releaseMode: "required",
  runtimeState: "enabled",
  sourceRoots: ["server/vault-quest/"],
  requirements: {
    migrations: [
      { name: "0000_next_mister_fear.sql", estate: "vault-quest", order: 14 },
      { name: "0001_equal_iron_fist.sql", estate: "vault-quest", order: 15 },
      { name: "0002_blushing_overlord.sql", estate: "vault-quest", order: 16 },
      { name: "0003_character_bible.sql", estate: "vault-quest", order: 17 },
      { name: "0004_reference_pack.sql", estate: "vault-quest", order: 18 },
      { name: "0005_identity_score.sql", estate: "vault-quest", order: 19 },
      { name: "0006_description_status.sql", estate: "vault-quest", order: 20 },
      { name: "0007_production_studio.sql", estate: "vault-quest", order: 21 },
      { name: "0008_export_jobs.sql", estate: "vault-quest", order: 22 },
      { name: "0009_generation_requests.sql", estate: "vault-quest", order: 23 },
      { name: "0010_artwork_revisions.sql", estate: "vault-quest", order: 24 },
      { name: "0011_feature_flags.sql", estate: "vault-quest", order: 25 },
      { name: "0012_export_job_payload.sql", estate: "vault-quest", order: 26 },
      { name: "0013_vq_config.sql", estate: "vault-quest", order: 27 },
      { name: "0014_artwork_revision_events.sql", estate: "vault-quest", order: 28 },
      { name: "0015_feature_flags_generation_types.sql", estate: "vault-quest", order: 29 },
      { name: "0016_schema_baseline_authority.sql", estate: "vault-quest", order: 30 },
    ],
    relations: [
      { name: "public.vq_ai_generations", order: 23 },
      { name: "public.vq_artwork_candidates", order: 24 },
      { name: "public.vq_artwork_revision_events", order: 25 },
      { name: "public.vq_artwork_revisions", order: 26 },
      { name: "public.vq_asset_library", order: 27 },
      { name: "public.vq_card_revisions", order: 28 },
      { name: "public.vq_cards", order: 29 },
      { name: "public.vq_character_revisions", order: 30 },
      { name: "public.vq_characters", order: 31 },
      { name: "public.vq_config", order: 32 },
      { name: "public.vq_elements", order: 33 },
      { name: "public.vq_export_jobs", order: 34 },
      { name: "public.vq_families", order: 35 },
      { name: "public.vq_family_rules", order: 36 },
      { name: "public.vq_feature_flags", order: 37 },
      { name: "public.vq_game_config", order: 38 },
      { name: "public.vq_generation_requests", order: 39 },
      { name: "public.vq_pack_config", order: 40 },
      { name: "public.vq_packaging_items", order: 41 },
      { name: "public.vq_print_exports", order: 42 },
      { name: "public.vq_production_stages", order: 43 },
      { name: "public.vq_qa_checks", order: 44 },
      { name: "public.vq_release_state", order: 45 },
      { name: "public.vq_releases", order: 46 },
      { name: "public.vq_set_settings", order: 47 },
      { name: "public.vq_sets", order: 48 },
    ],
    triggers: [],
    environment: [],
    runtimeSignals: [{ name: "vault_quest_database_authority", order: 4 }],
  },
} as const;
