/**
 * Claim code → Vault Club ownership — authority and fail-closed proof.
 *
 * Exercises the REAL shipped surface (`storage.validateClaimCode`,
 * `storage.createClaimVerification`, `storage.completeClaimByToken`) against a
 * DISPOSABLE PostgreSQL 17 cluster. `MINTVAULT_DATABASE_URL` is pointed at that
 * cluster BEFORE server/db.ts is imported, so the production module graph
 * (config → pool → drizzle → storage) is the code under test. No source-string
 * assertions; no staging or production database is touched.
 *
 * WHAT THIS SUITE EXISTS TO PIN — the defect found on production 2026-08-23:
 *
 *   completeClaimByToken() re-checked stolen / already-claimed / code-used, but
 *   NOT `status`. The front door (validateClaimCode) requires status='active',
 *   and a verification token stays valid for 24 hours — so a certificate VOIDED
 *   inside that window could still be claimed through the stale link, writing a
 *   real ownership row against an invalid certificate. Reproduced on staging:
 *   MV578 voided, stale token → 302 …/claim?success=true and
 *   ownership_status='claimed'.
 *
 * `denies a claim on a certificate voided after the link was issued` is the
 * regression: it FAILS against the pre-fix behaviour and passes after.
 */
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { Client, Pool } from "pg";
import { startPostgres17, type DisposablePostgres17 } from "./helpers/postgres17-cluster";
import { stubDdlForTable } from "./helpers/certificates-stub";

let cluster: DisposablePostgres17 | null = null;
let pool: Pool | null = null;
let admin: Client | null = null;

// The real production module, imported only after the env var is redirected.
let storage: typeof import("../server/storage").storage;

const CERT = "MV5001";
const OWNER = "owner@claim-authority.test";
const OTHER = "someone-else@claim-authority.test";

/** The four tables the claim path touches, derived from shared/schema.ts so they cannot drift. */
async function createSchema(c: Client): Promise<void> {
  const { certificates, users, claimVerifications, ownershipHistory } = await import("../shared/schema");
  const { createCertificatesStub } = await import("./helpers/certificates-stub");
  void certificates;

  await createCertificatesStub(c, "postgres");
  await c.query(stubDdlForTable(users, "users"));
  await c.query(stubDdlForTable(claimVerifications, "claim_verifications"));
  await c.query(stubDdlForTable(ownershipHistory, "ownership_history"));

  // Drizzle's `.defaultNow()` / `sql\`gen_random_uuid()\`` defaults are SQL-side: the ORM sends no
  // value on insert and relies on the column default, so the stub must carry them or every insert
  // writes NULL into a column production never sees NULL in.
  /*
   * `claim_code` — the PLAINTEXT code — is written by storage.generateClaimCode() through raw SQL
   * and is NOT modelled in shared/schema.ts, so the derived DDL above cannot know about it. Named
   * explicitly rather than silently added, because the gap is worth seeing: production stores the
   * claim code in clear next to its SHA-256 hash, and getOrGenerateClaimCode() reads the clear
   * value back when re-rendering a claim insert.
   */
  await c.query(`ALTER TABLE certificates ADD COLUMN IF NOT EXISTS claim_code text`);

  await c.query(`ALTER TABLE users ALTER COLUMN id SET DEFAULT gen_random_uuid()`);
  await c.query(`ALTER TABLE users ALTER COLUMN created_at SET DEFAULT now()`);
  await c.query(`ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT now()`);
  await c.query(`ALTER TABLE claim_verifications ALTER COLUMN created_at SET DEFAULT now()`);
  await c.query(`ALTER TABLE ownership_history ALTER COLUMN created_at SET DEFAULT now()`);
  await c.query(`ALTER TABLE ownership_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`).catch(() => {});
}

/** Put the certificate back to a clean, claimable state and clear the ledgers. */
async function resetCert(p: Pool, opts: { status?: string; stolen?: string | null } = {}): Promise<string> {
  await p.query(`DELETE FROM ownership_history`);
  await p.query(`DELETE FROM claim_verifications`);
  await p.query(`DELETE FROM users`);
  await p.query(`DELETE FROM certificates`);
  await p.query(
    `INSERT INTO certificates (certificate_number, status, ownership_status, stolen_status, card_name)
     VALUES ($1, $2, 'unclaimed', $3, 'Test Card')`,
    [CERT, opts.status ?? "active", opts.stolen ?? null]
  );
  return storage.generateClaimCode(CERT);
}

async function certRow(p: Pool) {
  const r = await p.query(
    `SELECT status, ownership_status, owner_email, current_owner_user_id, claim_code_used_at
     FROM certificates WHERE certificate_number = $1`,
    [CERT]
  );
  return r.rows[0];
}

async function historyCount(p: Pool): Promise<number> {
  const r = await p.query<{ n: string }>(`SELECT COUNT(*) n FROM ownership_history`);
  return Number(r.rows[0].n);
}

beforeAll(async () => {
  cluster = await startPostgres17("claim-ownership-authority");
  process.env.MINTVAULT_DATABASE_URL = cluster.url;
  admin = new Client({ connectionString: cluster.url, ssl: false });
  await admin.connect();
  await createSchema(admin);
  pool = new Pool({ connectionString: cluster.url, max: 8, ssl: false });
  storage = (await import("../server/storage")).storage;
}, 120_000);

afterAll(async () => {
  await pool?.end().catch(() => {});
  await admin?.end().catch(() => {});
  await cluster?.stop().catch(() => {});
});

describe("claim code → ownership (real storage, real PostgreSQL 17)", () => {
  beforeEach(async () => {
    await resetCert(pool!);
  });

  it("is backed by a real disposable cluster (non-vacuous)", async () => {
    const r = await pool!.query<{ server_version: string }>("SHOW server_version");
    expect(r.rows[0].server_version).toMatch(/^17\./);
    expect(cluster!.url).toMatch(/127\.0\.0\.1/);
  });

  it("commits ownership exactly once for a valid claim", async () => {
    const code = await resetCert(pool!);
    expect(await storage.validateClaimCode(CERT, code)).toBe(true);

    const token = await storage.createClaimVerification(CERT, OWNER, "Real Owner", false);
    const result = await storage.completeClaimByToken(token);

    expect(result.success).toBe(true);
    const cert = await certRow(pool!);
    expect(cert.ownership_status).toBe("claimed");
    expect(cert.owner_email).toBe(OWNER);
    expect(cert.current_owner_user_id).toBeTruthy();
    expect(cert.claim_code_used_at).toBeTruthy();
    expect(await historyCount(pool!)).toBe(1);
  });

  it("binds ownership to the verified email, and the collection query returns it", async () => {
    const code = await resetCert(pool!);
    await storage.completeClaimByToken(await storage.createClaimVerification(CERT, OWNER, null, false));
    void code;

    // The exact predicate /api/customer/certificates runs (getCertificatesByEmail, owned branch).
    const owned = await pool!.query(
      `SELECT certificate_number FROM certificates
       WHERE LOWER(owner_email) = LOWER($1) AND ownership_status = 'claimed'
         AND status != 'voided' AND deleted_at IS NULL`,
      [OWNER]
    );
    expect(owned.rows.map((r) => r.certificate_number)).toEqual([CERT]);

    const notOwned = await pool!.query(
      `SELECT certificate_number FROM certificates WHERE LOWER(owner_email) = LOWER($1)`,
      [OTHER]
    );
    expect(notOwned.rows).toHaveLength(0);
  });

  it("REGRESSION: denies a claim on a certificate voided after the link was issued", async () => {
    await resetCert(pool!);
    // Link minted while the certificate is still active — this is the 24h window.
    const token = await storage.createClaimVerification(CERT, OWNER, null, false);
    await pool!.query(`UPDATE certificates SET status = 'voided' WHERE certificate_number = $1`, [CERT]);

    const result = await storage.completeClaimByToken(token);

    expect(result.success).toBe(false);
    const cert = await certRow(pool!);
    expect(cert.ownership_status).toBe("unclaimed");
    expect(cert.current_owner_user_id).toBeNull();
    expect(cert.owner_email).toBeNull();
    expect(cert.claim_code_used_at).toBeNull();
    expect(await historyCount(pool!)).toBe(0);
  });

  it("denies a claim on a certificate reported stolen after the link was issued", async () => {
    await resetCert(pool!);
    const token = await storage.createClaimVerification(CERT, OWNER, null, false);
    await pool!.query(`UPDATE certificates SET stolen_status = 'reported_stolen' WHERE certificate_number = $1`, [
      CERT,
    ]);

    const result = await storage.completeClaimByToken(token);

    expect(result.success).toBe(false);
    expect((await certRow(pool!)).ownership_status).toBe("unclaimed");
    expect(await historyCount(pool!)).toBe(0);
  });

  it("replaying the same verification token does not write a second ownership row", async () => {
    await resetCert(pool!);
    const token = await storage.createClaimVerification(CERT, OWNER, null, false);
    expect((await storage.completeClaimByToken(token)).success).toBe(true);

    const replay = await storage.completeClaimByToken(token);

    expect(replay.success).toBe(false);
    expect(await historyCount(pool!)).toBe(1);
    expect((await certRow(pool!)).owner_email).toBe(OWNER);
  });

  it("a second person cannot claim an already-claimed certificate", async () => {
    await resetCert(pool!);
    await storage.completeClaimByToken(await storage.createClaimVerification(CERT, OWNER, null, false));

    const attacker = await storage.createClaimVerification(CERT, OTHER, null, false);
    const result = await storage.completeClaimByToken(attacker);

    expect(result.success).toBe(false);
    const cert = await certRow(pool!);
    expect(cert.owner_email).toBe(OWNER);
    expect(await historyCount(pool!)).toBe(1);
  });

  it("an invalid, blank or unknown claim code never validates", async () => {
    await resetCert(pool!);
    expect(await storage.validateClaimCode(CERT, "AAAABBBBCCCC")).toBe(false);
    expect(await storage.validateClaimCode(CERT, "")).toBe(false);
    expect(await storage.validateClaimCode("MV999999", "AAAABBBBCCCC")).toBe(false);
    expect((await certRow(pool!)).ownership_status).toBe("unclaimed");
  });

  it("a certificate with no claim code stored can never be claimed (production data gap)", async () => {
    await resetCert(pool!);
    await pool!.query(
      `UPDATE certificates SET claim_code = NULL, claim_code_hash = NULL WHERE certificate_number = $1`,
      [CERT]
    );
    // 354 of 832 active production certificates were in exactly this state on 2026-08-23.
    expect(await storage.validateClaimCode(CERT, "ANYCODEATALL")).toBe(false);
  });

  it("REGRESSION: a reprint returns the SAME code and never rotates a printed credential", async () => {
    const original = await resetCert(pool!);

    // Reprint while unclaimed — the ordinary case.
    expect(await storage.getOrGenerateClaimCode(CERT)).toBe(original);

    // Reprint after the card has been claimed. The printed insert is still the
    // buyer's credential for a transfer, so this must NOT mint a new one.
    await storage.completeClaimByToken(await storage.createClaimVerification(CERT, OWNER, null, false));
    expect(await storage.getOrGenerateClaimCode(CERT)).toBe(original);

    // And that same printed code must still authorise a buyer-initiated transfer.
    const transfer = await storage.validateClaimCodeForTransfer(CERT, original);
    expect(transfer.valid).toBe(true);
    expect(transfer.currentOwnerEmail).toBe(OWNER);
  });

  it("REGRESSION: a code is never issued unless the write is confirmed to have landed", async () => {
    // No such certificate — the UPDATE matches zero rows. Before the fix this
    // returned a valid-looking code that a caller would print onto a physical
    // insert the server had no record of.
    await expect(storage.generateClaimCode("MV-DOES-NOT-EXIST")).rejects.toThrow(/would not be recoverable/);

    const orphan = await pool!.query(
      `SELECT COUNT(*)::int n FROM certificates WHERE certificate_number = 'MV-DOES-NOT-EXIST'`
    );
    expect(orphan.rows[0].n).toBe(0);
  });

  it("REGRESSION: issuing a claim credential must NOT reset a pending ownership transfer", async () => {
    /*
     * THE DEFECT. generateClaimCode wrote
     *
     *   ownership_status = CASE WHEN ownership_status = 'claimed' THEN ownership_status ELSE 'unclaimed' END
     *
     * which preserved `claimed` and flattened EVERYTHING ELSE to `unclaimed` — including
     * `transfer_pending`. So issuing or rotating a credential on a card that was mid-transfer
     * silently destroyed the transfer state: the pending handover simply stopped existing, with no
     * audit of an ownership decision because nobody had made one.
     *
     * The invariant: a claim-credential operation is not an ownership decision. Printing,
     * reprinting, recovering or rotating a credential must leave ownership exactly as it was.
     */
    await resetCert(pool!);
    await pool!.query(
      `UPDATE certificates SET ownership_status = 'transfer_pending' WHERE certificate_number = $1`,
      [CERT]
    );

    await storage.generateClaimCode(CERT);

    const after = await pool!.query<{ ownership_status: string }>(
      `SELECT ownership_status FROM certificates WHERE certificate_number = $1`,
      [CERT]
    );
    expect(after.rows[0].ownership_status).toBe("transfer_pending");
  });

  it("REGRESSION: the print path leaves every ownership state untouched", async () => {
    // getOrGenerateClaimCode reuses an existing credential, but on a certificate that has none it
    // mints one — and that mint must not become a back door into ownership either.
    for (const state of ["unclaimed", "transfer_pending", "stolen"] as const) {
      await resetCert(pool!);
      await pool!.query(
        `UPDATE certificates SET claim_code = NULL, claim_code_hash = NULL, ownership_status = $2
          WHERE certificate_number = $1`,
        [CERT, state]
      );
      await storage.getOrGenerateClaimCode(CERT);
      const after = await pool!.query<{ ownership_status: string }>(
        `SELECT ownership_status FROM certificates WHERE certificate_number = $1`,
        [CERT]
      );
      expect(after.rows[0].ownership_status, `${state} must survive a first mint`).toBe(state);
    }
  });

  it("an explicit rotation still replaces the credential, and the old one stops working", async () => {
    const original = await resetCert(pool!);
    const rotated = await storage.generateClaimCode(CERT);

    expect(rotated).not.toBe(original);
    expect(await storage.validateClaimCode(CERT, original)).toBe(false);
    expect(await storage.validateClaimCode(CERT, rotated)).toBe(true);
  });

  it("issuing a credential leaves 'claimed' and 'unclaimed' exactly as they were", async () => {
    await resetCert(pool!);
    await storage.generateClaimCode(CERT);
    expect((await certRow(pool!)).ownership_status).toBe("unclaimed");

    await pool!.query(`UPDATE certificates SET ownership_status = 'claimed' WHERE certificate_number = $1`, [CERT]);
    await storage.generateClaimCode(CERT);
    expect((await certRow(pool!)).ownership_status).toBe("claimed");
  });

  it("REGRESSION: refuses to reprint a recovered hash-only credential rather than rotating it", async () => {
    await resetCert(pool!);
    // A credential recovered from a physical insert exists as a hash alone — the code itself lives
    // on paper in a customer's hands and is not readable here.
    await pool!.query(`UPDATE certificates SET claim_code = NULL WHERE certificate_number = $1`, [CERT]);

    await expect(storage.getOrGenerateClaimCode(CERT)).rejects.toThrow(/not readable here/);

    // The credential must survive the refusal untouched.
    const after = await pool!.query<{ h: string }>(
      `SELECT claim_code_hash h FROM certificates WHERE certificate_number = $1`,
      [CERT]
    );
    expect(after.rows[0].h).toBeTruthy();
  });

  it("a hash-only credential still validates the original printed code", async () => {
    const original = await resetCert(pool!);
    await pool!.query(`UPDATE certificates SET claim_code = NULL WHERE certificate_number = $1`, [CERT]);

    // This is the whole point of a hash-only restore: the paper code keeps working.
    expect(await storage.validateClaimCode(CERT, original)).toBe(true);
    expect(await storage.validateClaimCode(CERT, "AAAABBBBCCCC")).toBe(false);
  });

  it("a claim code is accepted case-insensitively and trimmed", async () => {
    const code = await resetCert(pool!);
    expect(await storage.validateClaimCode(CERT, `  ${code.toLowerCase()}  `)).toBe(true);
  });
});
