/**
 * MVGS v1.4 GOLDEN VECTORS — semantic freeze.
 *
 * 95 grade vectors and 50 centering axis rows, generated by running the real
 * frozen authority and stored as immutable fixtures
 * (tests/fixtures/mvgs-v1_4-golden.json).
 *
 * These expectations were PROVEN equivalent to the code production was running
 * at release v1120 / 320c731a: the same inputs were scored against a worktree
 * checked out at that commit and every one of the 145 results matched exactly.
 * So this corpus is not "what the engine does today" — it is what production
 * actually graded ~700 real certificates with.
 *
 * The tests drive the production authority. They do not restate the formula:
 * a test that recomputes the maths proves only that two copies of a bug agree.
 *
 * IF ONE OF THESE FAILS: the frozen grading engine changed behaviour. That is
 * the alarm working. Do not update the fixture — fix the engine, or ship v1.5.
 */
import { describe, expect, it, vi } from "vitest";

vi.mock("../server/lib/mvgs-calibration", () => ({
  loadMvgsCalibration: async () => {
    throw new Error("the frozen v1.4 authority must never read calibration from the database");
  },
}));

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { scoreMvgsV1_4, gradeForScoreV1_4, tierNameV1_4, isPristineV1_4, MVGS_V1_4_VERSION } from "../shared/mvgs/v1_4";
import { centeringAxisGrade } from "../shared/centering";
import { remainingToGrade } from "../shared/mvgs-scoring";
import { centeringSubgrade } from "../shared/centering";
import { resolveDraftGradeAuthority } from "../server/lib/draft-grade-authority";
import { buildVectorInputs } from "../scripts/mvgs/golden-inputs";

interface Golden {
  rulesVersion: string;
  corpusVersion: number;
  vectors: Array<{ id: string; description: string; expected: Record<string, unknown> }>;
  centeringAxes: Record<string, { front: number; back: number }>;
}
const GOLDEN = JSON.parse(readFileSync(join(process.cwd(), "tests/fixtures/mvgs-v1_4-golden.json"), "utf8")) as Golden;

describe("golden corpus integrity", () => {
  it("is the v1.4 corpus and is not empty", () => {
    expect(GOLDEN.rulesVersion).toBe(MVGS_V1_4_VERSION);
    expect(GOLDEN.vectors.length).toBeGreaterThanOrEqual(90);
    expect(Object.keys(GOLDEN.centeringAxes).length).toBe(50);
  });

  it("the corpus still describes exactly the declared input set — no case silently dropped", () => {
    const inputIds = buildVectorInputs()
      .map((c) => c.id)
      .sort();
    expect(GOLDEN.vectors.map((v) => v.id).sort()).toEqual(inputIds);
  });

  it("covers every grade rung the standard publishes, including all half grades", () => {
    const grades = new Set(GOLDEN.vectors.map((v) => (v.expected as { overall: number }).overall));
    for (const g of [10, 9.5, 9, 8.5, 8, 7.5, 7, 6.5, 6, 5.5, 5, 4.5, 4, 3.5, 3, 2.5, 2, 1.5, 1]) {
      expect(grades.has(g), `golden corpus does not cover grade ${g}`).toBe(true);
    }
  });
});

describe("every golden vector still scores identically through the real authority", () => {
  const inputs = new Map(buildVectorInputs().map((c) => [c.id, c.input]));

  for (const vector of GOLDEN.vectors) {
    it(`${vector.id} — ${vector.description}`, () => {
      const input = inputs.get(vector.id)!;
      const r = scoreMvgsV1_4(input);
      const overall = gradeForScoreV1_4(r.score);
      const subgrades = {
        centering: centeringSubgrade(
          input.centeringFrontLr,
          input.centeringFrontTb,
          input.centeringBackLr,
          input.centeringBackTb
        ).subgrade,
        corners: remainingToGrade(25 - Math.abs(r.deductions.corners ?? 0)),
        edges: remainingToGrade(25 - Math.abs(r.deductions.edges ?? 0)),
        surface: remainingToGrade(25 - Math.abs(r.deductions.surface ?? 0)),
      };
      expect({
        score: r.score,
        overall,
        tier: tierNameV1_4(overall),
        label: r.grade,
        subgrades,
        deductions: r.deductions,
        ceiling: r.ceiling,
        edgesSubgradeFromWhitening: r.edgesSubgradeFromWhitening,
        tearForceNotGraded: r.tearForceNotGraded,
        pristine: isPristineV1_4(subgrades, overall, r.deductions),
      }).toEqual(vector.expected);
    });
  }
});

describe("centering — every axis value from 50/50 to 99/1 is frozen", () => {
  it("front and back band grades match the golden corpus at every ratio", () => {
    const drift: string[] = [];
    for (const [ratio, expected] of Object.entries(GOLDEN.centeringAxes)) {
      const front = centeringAxisGrade(ratio, "front");
      const back = centeringAxisGrade(ratio, "back");
      if (front !== expected.front) drift.push(`front ${ratio}: golden ${expected.front}, engine ${front}`);
      if (back !== expected.back) drift.push(`back ${ratio}: golden ${expected.back}, engine ${back}`);
    }
    expect(drift, `centering bands moved:\n${drift.join("\n")}`).toEqual([]);
  });

  it("the published named boundaries specifically", () => {
    expect(centeringAxisGrade("50/50", "front")).toBe(10);
    expect(centeringAxisGrade("52/48", "front")).toBe(10);
    expect(centeringAxisGrade("54/46", "front")).toBe(10);
    expect(centeringAxisGrade("55/45", "front")).toBe(10);
    expect(centeringAxisGrade("56/44", "front")).toBe(9);
    expect(centeringAxisGrade("75/25", "back")).toBe(10);
    expect(centeringAxisGrade("76/24", "back")).toBe(9);
  });
});

/**
 * Staff and Partner both persist through applyCertGradeDraft ->
 * resolveDraftGradeAuthority. Driving the authority directly is therefore
 * driving the only grade producer either workflow has.
 */
describe("Staff and Partner resolve through the one frozen authority", () => {
  const observations = (over: Record<string, unknown> = {}) => ({
    gradeType: "numeric",
    authStatus: "genuine",
    centeringFrontLr: "50/50",
    centeringFrontTb: "50/50",
    centeringBackLr: "50/50",
    centeringBackTb: "50/50",
    cornerValues: {},
    edgeValues: {},
    surfaceValues: { hasCrease: false, hasTear: false },
    defects: [],
    ...over,
  });

  const CASES: Array<[string, Record<string, unknown>, string, string]> = [
    ["flawless", { defects: [] }, "10", "Gem Mint"],
    ["one front corner", { defects: [{ tier: "D1", mvgsCode: "CN", zone: "FC1" }] }, "9.5", "Mint+"],
    [
      "two front corners",
      {
        defects: [
          { tier: "D1", mvgsCode: "CN", zone: "FC1" },
          { tier: "D1", mvgsCode: "CN", zone: "FC2" },
        ],
      },
      "8.5",
      "NM-Mint+",
    ],
    [
      "five surface SC",
      { defects: Array.from({ length: 5 }, () => ({ tier: "D1", mvgsCode: "SC", zone: "FA" })) },
      "7.5",
      "NM+",
    ],
  ];

  for (const [name, over, expectedGrade, expectedTier] of CASES) {
    it(`${name} → ${expectedGrade} (${expectedTier}), stamped ${MVGS_V1_4_VERSION}`, async () => {
      const authority = await resolveDraftGradeAuthority(observations(over), {});
      expect(authority.overall).toBe(expectedGrade);
      expect(authority.label).toBe(expectedTier);
      expect(authority.rulesVersion).toBe(MVGS_V1_4_VERSION);
    });
  }

  it("a browser-supplied grade is discarded by the frozen authority", async () => {
    const a = await resolveDraftGradeAuthority(
      observations({ defects: [{ tier: "D1", mvgsCode: "CN", zone: "FC1" }] }),
      {
        overall_grade: 10,
        grade_centering: 10,
        grade_corners: 10,
        grade_edges: 10,
        grade_surface: 10,
      }
    );
    expect(a.overall).toBe("9.5");
    expect(a.subgrades.corners).toBe(9);
  });
});
