import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { Client } from "pg";
import { applyMigrations, listMigrationFiles } from "../scripts/db/migrate";

const TEST_URL = process.env.SCANNER_MIGRATION_TEST_DATABASE_URL || "";

function assertDisposableUrl(url: string): void {
  const parsed = new URL(url);
  if (
    !["127.0.0.1", "localhost"].includes(parsed.hostname) ||
    parsed.port !== "5432" ||
    !/^\/mintvault_dgn_release_[a-z0-9_]+$/i.test(parsed.pathname)
  ) {
    throw new Error(
      "SCANNER_MIGRATION_TEST_DATABASE_URL must name a local mintvault_dgn_release_* disposable database on port 5432"
    );
  }
}

const suite = TEST_URL ? describe : describe.skip;

suite("scanner production migrations 0045–0047", () => {
  let client: Client;

  beforeAll(async () => {
    assertDisposableUrl(TEST_URL);
    client = new Client({ connectionString: TEST_URL });
    await client.connect();
    await client.query(`
      CREATE EXTENSION IF NOT EXISTS pgcrypto;
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'partner_runtime') THEN
          CREATE ROLE partner_runtime NOLOGIN;
        END IF;
      END $$;
      CREATE TABLE certificates (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        certificate_number text NOT NULL UNIQUE,
        deleted_at timestamptz
      );
      CREATE TABLE partner_organisations (id uuid PRIMARY KEY);
      CREATE TABLE partner_locations (
        id uuid PRIMARY KEY,
        tenant_id uuid NOT NULL REFERENCES partner_organisations(id) ON DELETE RESTRICT
      );
      CREATE OR REPLACE FUNCTION partner_current_tenant() RETURNS uuid
        LANGUAGE sql STABLE AS $$ SELECT NULL::uuid $$;
    `);
  });

  afterAll(async () => {
    await client?.end().catch(() => {});
  });

  it("applies only the approved additive migrations and journals an idempotent replay", async () => {
    const files = listMigrationFiles().filter((file) => ["0045", "0046", "0047"].includes(file.number));
    expect(files.map((file) => file.filename)).toEqual([
      "0045_partner_stations.sql",
      "0046_scanner_processing_jobs.sql",
      "0047_scanner_evidence_staging.sql",
    ]);

    const first = await applyMigrations(client as never, files);
    expect(first.applied).toEqual(files.map((file) => file.filename));

    const tables = await client.query<{ table_name: string }>(`
      SELECT table_name
        FROM information_schema.tables
       WHERE table_schema = 'public'
         AND table_name IN (
           'partner_stations', 'partner_station_calibrations', 'partner_station_events',
           'scanner_processing_jobs', 'scanner_capture_sessions',
           'scanner_evidence_staging', 'certificate_image_evidence'
         )
       ORDER BY table_name
    `);
    expect(tables.rows.map((row) => row.table_name)).toEqual([
      "certificate_image_evidence",
      "partner_station_calibrations",
      "partner_station_events",
      "partner_stations",
      "scanner_capture_sessions",
      "scanner_evidence_staging",
      "scanner_processing_jobs",
    ]);

    const constraints = await client.query<{ conname: string }>(`
      SELECT conname
        FROM pg_constraint
       WHERE conrelid = 'certificate_image_evidence'::regclass
       ORDER BY conname
    `);
    expect(constraints.rows.map((row) => row.conname)).toContain("certificate_image_evidence_side_check");
    expect(constraints.rows.map((row) => row.conname)).toContain("certificate_image_evidence_evidence_class_check");

    const indexes = await client.query<{ indexname: string; indexdef: string }>(`
      SELECT indexname, indexdef
        FROM pg_indexes
       WHERE schemaname = 'public'
         AND indexname IN (
           'uq_certificate_image_evidence_current_side',
           'uq_scanner_capture_one_active_target',
           'uq_scanner_evidence_staging_active_session',
           'uq_certificates_ingest_idem'
         )
       ORDER BY indexname
    `);
    expect(indexes.rows.map((row) => row.indexname)).toEqual([
      "uq_certificate_image_evidence_current_side",
      "uq_certificates_ingest_idem",
      "uq_scanner_capture_one_active_target",
      "uq_scanner_evidence_staging_active_session",
    ]);
    expect(
      indexes.rows.find((row) => row.indexname === "uq_certificate_image_evidence_current_side")?.indexdef
    ).toMatch(/WHERE is_current/);
    const activeCaptureIndex = indexes.rows.find(
      (row) => row.indexname === "uq_scanner_capture_one_active_target"
    )?.indexdef;
    expect(activeCaptureIndex).toContain("certificate_id, side");
    expect(activeCaptureIndex).toContain("armed");
    expect(activeCaptureIndex).toContain("claimed");
    expect(activeCaptureIndex).toContain("capturing");

    const replay = await applyMigrations(client as never, files);
    expect(replay.applied).toEqual([]);
  });
});
