/**
 * agent-plist.js — SINGLE SOURCE OF TRUTH for the com.mintvault.scanner
 * LaunchAgent plist.
 *
 * All absolute paths are computed at runtime from this file's own location —
 * no scattered hardcoded copies. Both the menu-bar app (main.js, the Repair
 * tier of the reset) and the standalone reset helper (reset-agent.sh, via the
 * `--write` CLI below) render the plist from the SAME `renderPlist()`, so the
 * installed agent and the repaired agent can never drift.
 *
 * NB: this is the GUI menu-bar app, so ProcessType=Interactive (NOT Background
 * — that was the old headless watcher.mjs daemon, now decommissioned).
 * KeepAlive uses the {Crashed, SuccessfulExit:false} form: auto-respawn on a
 * crash or non-zero exit, but allow a clean operator quit.
 */

const os = require("node:os");
const path = require("node:path");
const fs = require("node:fs");

const LABEL = "com.mintvault.scanner";

function paths() {
  const appDir = path.resolve(__dirname, ".."); // …/scripts/scanner-app
  const home = os.homedir();
  const packagedContents = path.resolve(appDir, "..", "..");
  const packagedExecutable = path.join(packagedContents, "MacOS", "MintVault Scanner");
  const isPackaged =
    fs.existsSync(path.join(packagedContents, "Info.plist")) && fs.existsSync(packagedExecutable);
  const wrapper = path.join(appDir, "launchd-wrapper.sh");
  return {
    label: LABEL,
    appDir,
    wrapper,
    packagedExecutable,
    // A shipped bundle deliberately excludes the development Electron package. Its LaunchAgent
    // must therefore start the bundle executable, not the development wrapper that expects
    // node_modules/.bin/electron. Source-checkout development retains the wrapper unchanged.
    launcher: isPackaged ? packagedExecutable : wrapper,
    home,
    uid: typeof process.getuid === "function" ? process.getuid() : null,
    plistPath: path.join(home, "Library", "LaunchAgents", `${LABEL}.plist`),
    // The operator-facing log (tray "Show logs" target). Reset tiers + the
    // app's stdout/stderr all land here so there is one log to read.
    logPath: path.join(home, "mintvault-scans", "scanner-app.log"),
  };
}

function renderPlist() {
  const p = paths();
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/scanner-app/lib/agent-plist.js — single source of truth.
     Do not hand-edit; regenerate via the reset's Repair tier or \`node lib/agent-plist.js --write\`. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${p.label}</string>

    <key>ProgramArguments</key>
    <array>
        <string>${p.launcher}</string>
    </array>

    <key>WorkingDirectory</key>
    <string>${p.appDir}</string>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
        <key>Crashed</key>
        <true/>
        <key>SuccessfulExit</key>
        <false/>
    </dict>

    <key>ProcessType</key>
    <string>Interactive</string>

    <key>StandardOutPath</key>
    <string>${p.logPath}</string>

    <key>StandardErrorPath</key>
    <string>${p.logPath}</string>
</dict>
</plist>
`;
}

/** Write the plist to ~/Library/LaunchAgents and chmod 644. Returns the path. */
function writePlist() {
  const p = paths();
  fs.mkdirSync(path.dirname(p.plistPath), { recursive: true });
  fs.writeFileSync(p.plistPath, renderPlist(), { mode: 0o644 });
  fs.chmodSync(p.plistPath, 0o644);
  return p.plistPath;
}

module.exports = { LABEL, paths, renderPlist, writePlist };

// CLI: `node lib/agent-plist.js --write` — used by reset-agent.sh's Repair tier
// so the shell helper and the app share ONE renderer.
if (require.main === module && process.argv.includes("--write")) {
  try {
    const out = writePlist();
    process.stdout.write(out + "\n");
    process.exit(0);
  } catch (err) {
    process.stderr.write(`agent-plist: write failed: ${err.message}\n`);
    process.exit(1);
  }
}
