-- P4 — GRADING CREDIT AUTHORITY: the (station_id, client_op_id) idempotency contract.
--
-- NUMBER SAFETY: 0082 follows 0078-0081 from this pass, all above the global high-water mark of 0077
-- discovered across every ref in the repository. The runner rejects duplicate numbers.
--
-- ============================================================================================
-- WHAT WAS MISSING
-- ============================================================================================
-- The existing credit engine is idempotent, but only on SERVER-DERIVED keys: every reservation is
-- keyed `partner-submission-credit:<submissionId>:<cardId>:<ordinal>`, deterministic because the
-- server already knows the submission. That works for the portal, where the client sends a
-- submission id and the server derives everything else.
--
-- It does NOT work for a Scanner station pressing NEW. There is no submission yet, so there is no
-- server-derivable key, and the operation the station is retrying is "start a new card" — an
-- operation whose whole identity is client-side. A dropped response, a double-click, a lost network
-- ack or an app restart mid-request all look identical to the server, and without a client-supplied
-- operation id each retry would reserve ANOTHER Grading Credit and mint ANOTHER Card Job.
--
-- `grep -rn 'partner_op_keys|client_op_id|clientOpId'` over server/, migrations/ and shared/ returned
-- ZERO hits before this migration: the contract simply did not exist.
--
-- ============================================================================================
-- WHY THE UNIQUE KEY IS (station_id, client_op_id) AND NOT (tenant_id, station_id, client_op_id)
-- ============================================================================================
-- A station belongs to exactly one tenant (partner_stations.tenant_id is NOT NULL), so adding
-- tenant_id to the key would not scope anything that is not already scoped — it would WEAKEN the
-- constraint, by allowing the same (station, client_op_id) pair to exist twice under two tenant ids.
-- The narrower key is the stronger guarantee. tenant_id is still carried on the row for RLS and for
-- the composite foreign key below.
--
-- ============================================================================================
-- WHY THE FOREIGN KEY IS COMPOSITE
-- ============================================================================================
-- (card_job_id, tenant_id) references partner_card_jobs(id, tenant_id) — the composite identity
-- 0080 declares for exactly this purpose. A single-column FK to the job id would let an op key in
-- tenant A point at tenant B's Card Job; with the composite key that row cannot be written at all.
-- Cross-tenant reference becomes structurally impossible rather than merely policed by RLS.
--
-- ============================================================================================
-- SHARED STATE, NOT PROCESS-LOCAL (invariant I19)
-- ============================================================================================
-- This is deliberately a TABLE and not an in-memory Map. Production runs a minimum of two Fly
-- Machines behind a load balancer: a station's retry can land on the other Machine from the one that
-- served the original request, and a rolling deploy discards process memory entirely. An in-process
-- idempotency cache would therefore fail exactly when it matters — on the retry — and double-spend a
-- Grading Credit. PostgreSQL is the only correct home for this.
--
-- MIXED-VERSION SAFETY (I17): purely additive — one new table. An OLD application version does not
-- know it exists; a NEW one uses it. Safe to apply before the deploy (expand -> migrate -> deploy).
--
-- ROLLBACK / DOWN-PATH: `DROP TABLE IF EXISTS partner_card_job_op_keys;`. Safe while no code writes
-- it; once live it becomes forward-fix only, since dropping it would re-open double-spend on retry.

CREATE TABLE IF NOT EXISTS partner_card_job_op_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES partner_organisations(id) ON DELETE RESTRICT,
  -- No FK to partner_stations: that table arrives in migration 0045, which is not present on every
  -- database this table must exist on. The station id is still authenticated by the server before
  -- any row is written, and the tenant FK plus RLS carry the isolation guarantee.
  station_id uuid NOT NULL,
  -- Opaque to the server. Generated by the station, stable across ITS retries of one NEW press.
  client_op_id text NOT NULL,

  -- The result being made idempotent: which Card Job this operation produced.
  card_job_id uuid NOT NULL,
  -- The reservation that funded it, recorded so a replay can return the whole lineage without
  -- re-deriving it.
  reservation_id uuid,

  /*
   * SHA-256 of the canonical request. A replay carrying the SAME op id but DIFFERENT parameters is
   * not a retry — it is a client bug or an attack, and returning the original job would silently
   * give the caller something it did not ask for. Same discipline the credit engine already applies
   * to its own idempotency keys (requestFingerprint / IDEMPOTENCY_CONFLICT).
   */
  request_fingerprint text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT chk_partner_card_job_op_keys_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_partner_card_job_op_keys_client_op_id CHECK (length(client_op_id) BETWEEN 8 AND 200),

  -- THE contract. One (station, client_op_id) can only ever have produced one Card Job.
  CONSTRAINT uq_partner_card_job_op_keys UNIQUE (station_id, client_op_id),

  -- Cross-tenant reference made structurally impossible (see header).
  CONSTRAINT fk_partner_card_job_op_keys_job
    FOREIGN KEY (card_job_id, tenant_id) REFERENCES partner_card_jobs(id, tenant_id) ON DELETE RESTRICT
);

-- One Card Job is produced by at most ONE start operation. Without this, two different client_op_ids
-- could both claim to have created the same job, which would make a replay ambiguous.
CREATE UNIQUE INDEX IF NOT EXISTS uq_partner_card_job_op_keys_job
  ON partner_card_job_op_keys (card_job_id);

CREATE INDEX IF NOT EXISTS idx_partner_card_job_op_keys_tenant
  ON partner_card_job_op_keys (tenant_id, created_at DESC);

-- ---------------------------------------------------------------------------------------------
-- Tenant isolation (invariant I6)
-- ---------------------------------------------------------------------------------------------
-- ENABLE + FORCE + one tenant policy, identical to every other partner table. FORCE matters: without
-- it the table OWNER is exempt from its own policy.
ALTER TABLE partner_card_job_op_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE partner_card_job_op_keys FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS partner_card_job_op_keys_tenant_isolation ON partner_card_job_op_keys;
CREATE POLICY partner_card_job_op_keys_tenant_isolation ON partner_card_job_op_keys
  USING (tenant_id = partner_current_tenant())
  WITH CHECK (tenant_id = partner_current_tenant());

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'partner_runtime') THEN
    -- No UPDATE and no DELETE: an idempotency record is write-once evidence. Allowing it to be
    -- rewritten would let a replay be re-pointed at a different Card Job, which is the whole thing
    -- this table exists to prevent.
    GRANT SELECT, INSERT ON public.partner_card_job_op_keys TO partner_runtime;
  END IF;
END$$;

-- Write-once, enforced rather than merely granted away: an owner-level connection (or any future
-- grant) still cannot rewrite or delete a recorded operation.
CREATE OR REPLACE FUNCTION partner_card_job_op_keys_append_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION 'partner_card_job_op_keys is append-only: % is not permitted', TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$;

DROP TRIGGER IF EXISTS trg_partner_card_job_op_keys_append_only ON partner_card_job_op_keys;
CREATE TRIGGER trg_partner_card_job_op_keys_append_only
  BEFORE UPDATE OR DELETE ON partner_card_job_op_keys
  FOR EACH ROW EXECUTE FUNCTION partner_card_job_op_keys_append_only();
ALTER TABLE partner_card_job_op_keys ENABLE ALWAYS TRIGGER trg_partner_card_job_op_keys_append_only;
