// server/staging-harness.ts
// Staging-only test harness — seed + reset endpoints for E2E dogfooding.
//
// CRITICAL: these functions write synthetic test data and hard-DELETE it on reset.
// Triple-layer guard (stagingOnlyGuard + requireAdmin + safety-limit count check)
// prevents accidental execution on prod. See the rule #14 exception comment in
// resetStagingData() for why hard DELETE is defensible here.

import crypto from "crypto";
import bcrypt from "bcryptjs";
import type { Request, Response, NextFunction } from "express";
import { db } from "./db";
import { sql } from "drizzle-orm";

// ── Constants ────────────────────────────────────────────────────────────────
const TEST_PASSWORD = "STAGING-TEST-HARNESS-9f8e7d6c";
const TEST_EMAIL_DOMAIN = "@staging-test.mintvault.dev";
const TEST_CERT_PREFIX = "MV900";
const RESET_SAFETY_LIMIT = 50;

// ── Triple-guard middleware ──────────────────────────────────────────────────
// Applied AFTER requireAdmin in the route chain. Both env-var checks must pass.
export function stagingOnlyGuard(req: Request, res: Response, next: NextFunction) {
  const appUrl = process.env.APP_URL || "";
  const stagingFlag = process.env.STAGING_ONLY;

  if (!appUrl.includes("mintvault-v2")) {
    return res.status(403).json({
      error: "Staging-only endpoint. APP_URL does not reference mintvault-v2. Refusing to run.",
      guardTripped: "APP_URL",
    });
  }
  if (stagingFlag !== "1") {
    return res.status(403).json({
      error: "Staging-only endpoint. STAGING_ONLY env var is not set to '1'. Refusing to run.",
      guardTripped: "STAGING_ONLY",
    });
  }
  next();
}

// ── Seed (e2e-v1 preset) ─────────────────────────────────────────────────────

export interface SeedResult {
  ok: true;
  dryRun: boolean;
  alreadySeeded?: boolean;
  inserted?: { customers: number; certs: number; transfers: number; vaultClubRows: number };
}

export async function seedE2Ev1(opts: { dryRun: boolean; adminEmail: string }): Promise<SeedResult> {
  const { dryRun, adminEmail } = opts;

  // Audit log BEFORE any SQL — captures intent even if a later query crashes
  await db.execute(sql`
    INSERT INTO audit_log (entity_type, entity_id, action, admin_user, details)
    VALUES ('staging_harness', 'seed-e2e-v1', ${dryRun ? "seed_dryrun" : "seed"},
            ${adminEmail}, ${JSON.stringify({ preset: "e2e-v1", dryRun })}::jsonb)
  `);

  // Idempotency check (skip on dry-run since nothing is being written)
  if (!dryRun) {
    const existing = await db.execute(sql`
      SELECT 1 FROM certificates WHERE certificate_number = 'MV900001' LIMIT 1
    `);
    if (existing.rows.length > 0) {
      return { ok: true, dryRun: false, alreadySeeded: true };
    }
  }

  // Dry-run short-circuit — expected counts without touching data
  if (dryRun) {
    return {
      ok: true,
      dryRun: true,
      inserted: { customers: 3, certs: 10, transfers: 5, vaultClubRows: 2 },
    };
  }

  // ── Real seeding ────────────────────────────────────────────────────────

  const passwordHash = await bcrypt.hash(TEST_PASSWORD, 10);

  // 3 test users — UUIDs auto-generated by the users table default
  const ownerEmail = `owner${TEST_EMAIL_DOMAIN}`;
  const incomingEmail = `incoming${TEST_EMAIL_DOMAIN}`;
  const adminEmailTest = `admin${TEST_EMAIL_DOMAIN}`;

  const ownerRes = await db.execute(sql`
    INSERT INTO users (email, role, display_name, password_hash, email_verified, email_verified_at)
    VALUES (${ownerEmail}, 'customer', 'Test Owner', ${passwordHash}, true, NOW())
    RETURNING id
  `);
  const ownerId = (ownerRes.rows[0] as any).id as string;

  const incomingRes = await db.execute(sql`
    INSERT INTO users (email, role, display_name, password_hash, email_verified, email_verified_at)
    VALUES (${incomingEmail}, 'customer', 'Test Incoming', ${passwordHash}, true, NOW())
    RETURNING id
  `);
  const incomingId = (incomingRes.rows[0] as any).id as string;

  await db.execute(sql`
    INSERT INTO users (email, role, display_name, password_hash, email_verified, email_verified_at)
    VALUES (${adminEmailTest}, 'admin', 'Test Admin', ${passwordHash}, true, NOW())
    RETURNING id
  `);

  // 10 test certs (MV900001–MV900010)
  const { generateReferenceNumber } = await import("./reference-number");

  const CERT_DEFS: Array<{
    certId: string;
    grade: string | null;
    gradeType: string;
    cardName: string;
    claimedBy: string | null;
  }> = [
    { certId: "MV900001", grade: "10", gradeType: "numeric", cardName: "Test Charizard (Gem Mint)",  claimedBy: ownerId },
    { certId: "MV900002", grade: "9",  gradeType: "numeric", cardName: "Test Blastoise (Mint)",       claimedBy: ownerId },
    { certId: "MV900003", grade: "8",  gradeType: "numeric", cardName: "Test Venusaur (NM-MT)",       claimedBy: ownerId },
    { certId: "MV900004", grade: "7",  gradeType: "numeric", cardName: "Test Pikachu (NM)",           claimedBy: ownerId },
    { certId: "MV900005", grade: "6",  gradeType: "numeric", cardName: "Test Mewtwo (EX-MT)",         claimedBy: ownerId },
    { certId: "MV900006", grade: "10", gradeType: "numeric", cardName: "Test Lugia",                  claimedBy: null },
    { certId: "MV900007", grade: "9",  gradeType: "numeric", cardName: "Test Ho-Oh",                  claimedBy: null },
    { certId: "MV900008", grade: "8",  gradeType: "numeric", cardName: "Test Rayquaza",               claimedBy: null },
    { certId: "MV900009", grade: "10", gradeType: "numeric", cardName: "Test Mew (Incoming's Card)",  claimedBy: incomingId },
    { certId: "MV900010", grade: null, gradeType: "NO",      cardName: "Test Authentic-Only Card",    claimedBy: null },
  ];

  for (const d of CERT_DEFS) {
    const refNum = generateReferenceNumber();
    const isClaimed = d.claimedBy !== null;
    const ownEmail = isClaimed ? (d.claimedBy === ownerId ? ownerEmail : incomingEmail) : null;
    const ownName  = isClaimed ? (d.claimedBy === ownerId ? "Test Owner" : "Test Incoming") : null;
    const ownToken = isClaimed ? crypto.randomBytes(32).toString("hex") : null;
    const ownerStatus = isClaimed ? "claimed" : "unclaimed";

    await db.execute(sql`
      INSERT INTO certificates (
        certificate_number, grade, grade_type, card_name, label_type, status,
        ownership_status, current_owner_user_id, owner_email, owner_name,
        ownership_token, ownership_token_generated_at,
        reference_number, logbook_version, logbook_last_issued_at
      )
      VALUES (
        ${d.certId}, ${d.grade}, ${d.gradeType}, ${d.cardName}, 'Standard', 'active',
        ${ownerStatus}, ${d.claimedBy}, ${ownEmail}, ${ownName},
        ${ownToken}, ${isClaimed ? sql`NOW()` : sql`NULL`},
        ${refNum}, 1, ${isClaimed ? sql`NOW()` : sql`NULL`}
      )
    `);
  }

  // 5 transfers covering pending_owner, pending_incoming, pending_dispute, disputed, completed
  const TRANSFER_DEFS: Array<{ certId: string; status: string }> = [
    { certId: "MV900001", status: "pending_owner" },
    { certId: "MV900002", status: "pending_incoming" },
    { certId: "MV900003", status: "pending_dispute" },
    { certId: "MV900004", status: "disputed" },
    { certId: "MV900005", status: "completed" },
  ];

  for (const t of TRANSFER_DEFS) {
    const tokenHash = crypto.createHash("sha256").update(t.certId + Date.now()).digest("hex");
    const hasOwnerConfirmed = t.status !== "pending_owner";
    const hasDisputeWindow = ["pending_dispute", "disputed", "completed"].includes(t.status);
    const isDisputed = t.status === "disputed";
    const isCompleted = t.status === "completed";

    await db.execute(sql`
      INSERT INTO transfer_verifications (
        cert_id, from_email, to_email,
        owner_token_hash, owner_expires_at,
        flow_version, transfer_status,
        owner_confirmed_at,
        outgoing_keeper_user_id, incoming_keeper_user_id,
        dispute_deadline, disputed_at, disputed_by, dispute_reason,
        finalised_at
      )
      VALUES (
        ${t.certId}, ${ownerEmail}, ${incomingEmail},
        ${tokenHash}, NOW() + INTERVAL '1 day',
        'v2', ${t.status},
        ${hasOwnerConfirmed ? sql`NOW() - INTERVAL '2 hours'` : sql`NULL`},
        ${ownerId}, ${incomingId},
        ${hasDisputeWindow ? sql`NOW() + INTERVAL '14 days'` : sql`NULL`},
        ${isDisputed ? sql`NOW() - INTERVAL '30 minutes'` : sql`NULL`},
        ${isDisputed ? "incoming" : null},
        ${isDisputed ? "Test dispute reason — card condition does not match description" : null},
        ${isCompleted ? sql`NOW() - INTERVAL '1 hour'` : sql`NULL`}
      )
    `);
  }

  // 2 Vault Club rows via UPDATE on the users table (Vault Club columns live on users)
  await db.execute(sql`
    UPDATE users SET
      vault_club_tier = 'gold',
      vault_club_status = 'active',
      vault_club_started_at = NOW() - INTERVAL '30 days',
      vault_club_renews_at = NOW() + INTERVAL '30 days'
    WHERE email = ${ownerEmail}
  `);
  await db.execute(sql`
    UPDATE users SET
      vault_club_tier = 'silver',
      vault_club_status = 'past_due',
      vault_club_started_at = NOW() - INTERVAL '60 days',
      vault_club_grace_until = NOW() + INTERVAL '3 days'
    WHERE email = ${incomingEmail}
  `);

  return {
    ok: true,
    dryRun: false,
    inserted: { customers: 3, certs: 10, transfers: 5, vaultClubRows: 2 },
  };
}

// ── Reset ────────────────────────────────────────────────────────────────────

export class SafetyLimitExceeded extends Error {
  constructor(public totalCount: number, public limit: number) {
    super(`Reset would affect ${totalCount} rows — exceeds safety limit of ${limit}. Refusing.`);
    this.name = "SafetyLimitExceeded";
  }
}

export interface ResetCounts {
  transfers: number;
  claimVerifications: number;
  labelPrints: number;
  labelOverrides: number;
  reprintLog: number;
  ownershipHistory: number;
  stolenReports: number;
  certificates: number;
  customerMagicLinkTokens: number;
  passwordResetTokens: number;
  emailVerificationTokens: number;
  accountMagicLinkTokens: number;
  users: number;
  total: number;
}

export interface ResetResult {
  ok: true;
  dryRun: boolean;
  deleted: ResetCounts;
}

/**
 * Rule #14 exception (justified + documented):
 *
 * Hard DELETE is used here because the rows being removed are synthetic test
 * data generated by seedE2Ev1() — they never existed in production and contain
 * no real user-facing business data. The rule-#14 soft-delete pattern protects
 * real customer records; synthetic scaffolding is out of scope. The audit_log
 * row written at the top of this function preserves the trail (admin, timestamp,
 * intent, counts).
 *
 * The reset is scoped to two pattern matches only: cert_id LIKE 'MV900%' and
 * email LIKE '%@staging-test.mintvault.dev'. Neither can match real prod data
 * (prod cert range is MV1–MV141, real customer emails are @gmail.com etc.).
 * A secondary safety limit of 50 total rows catches any accidental WHERE-clause
 * corruption or unclassified new tables.
 */
export async function resetStagingData(opts: { dryRun: boolean; adminEmail: string }): Promise<ResetResult> {
  const { dryRun, adminEmail } = opts;

  // Audit log BEFORE any SQL
  await db.execute(sql`
    INSERT INTO audit_log (entity_type, entity_id, action, admin_user, details)
    VALUES ('staging_harness', 'reset-e2e-v1', ${dryRun ? "reset_dryrun" : "reset"},
            ${adminEmail}, ${JSON.stringify({ dryRun, prefix: TEST_CERT_PREFIX, domain: TEST_EMAIL_DOMAIN })}::jsonb)
  `);

  const certPat = `${TEST_CERT_PREFIX}%`;
  const emailPat = `%${TEST_EMAIL_DOMAIN}`;

  // Count matches per table BEFORE any delete — required for safety-limit check
  const counts: ResetCounts = {
    transfers: 0, claimVerifications: 0, labelPrints: 0, labelOverrides: 0,
    reprintLog: 0, ownershipHistory: 0, stolenReports: 0, certificates: 0,
    customerMagicLinkTokens: 0, passwordResetTokens: 0, emailVerificationTokens: 0,
    accountMagicLinkTokens: 0, users: 0, total: 0,
  };

  const asInt = (r: any): number => parseInt(r.rows[0]?.n ?? "0", 10);

  counts.transfers = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM transfer_verifications
    WHERE from_email LIKE ${emailPat} OR to_email LIKE ${emailPat} OR cert_id LIKE ${certPat}
  `));
  counts.claimVerifications = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM claim_verifications
    WHERE email LIKE ${emailPat} OR cert_id LIKE ${certPat}
  `));
  counts.labelPrints = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM label_prints WHERE cert_id LIKE ${certPat}
  `));
  counts.labelOverrides = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM label_overrides WHERE cert_id LIKE ${certPat}
  `));
  counts.reprintLog = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM reprint_log WHERE cert_id LIKE ${certPat}
  `));
  counts.ownershipHistory = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM ownership_history WHERE cert_id LIKE ${certPat}
  `));
  counts.stolenReports = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM stolen_reports WHERE cert_id LIKE ${certPat}
  `));
  counts.certificates = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM certificates WHERE certificate_number LIKE ${certPat}
  `));
  counts.customerMagicLinkTokens = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM customer_magic_link_tokens WHERE email LIKE ${emailPat}
  `));
  counts.passwordResetTokens = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM password_reset_tokens
    WHERE user_id IN (SELECT id FROM users WHERE email LIKE ${emailPat})
  `));
  counts.emailVerificationTokens = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM email_verification_tokens
    WHERE user_id IN (SELECT id FROM users WHERE email LIKE ${emailPat})
  `));
  counts.accountMagicLinkTokens = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM account_magic_link_tokens
    WHERE user_id IN (SELECT id FROM users WHERE email LIKE ${emailPat})
  `));
  counts.users = asInt(await db.execute(sql`
    SELECT COUNT(*)::int AS n FROM users WHERE email LIKE ${emailPat}
  `));

  counts.total =
    counts.transfers + counts.claimVerifications + counts.labelPrints +
    counts.labelOverrides + counts.reprintLog + counts.ownershipHistory +
    counts.stolenReports + counts.certificates + counts.customerMagicLinkTokens +
    counts.passwordResetTokens + counts.emailVerificationTokens +
    counts.accountMagicLinkTokens + counts.users;

  // Safety limit — catches corrupted WHERE clauses / forgotten tables
  if (counts.total > RESET_SAFETY_LIMIT) {
    throw new SafetyLimitExceeded(counts.total, RESET_SAFETY_LIMIT);
  }

  if (dryRun) {
    return { ok: true, dryRun: true, deleted: counts };
  }

  // ── Execute DELETE cascade in FK-safe order ───────────────────────────

  await db.execute(sql`
    DELETE FROM transfer_verifications
    WHERE from_email LIKE ${emailPat} OR to_email LIKE ${emailPat} OR cert_id LIKE ${certPat}
  `);
  await db.execute(sql`
    DELETE FROM claim_verifications
    WHERE email LIKE ${emailPat} OR cert_id LIKE ${certPat}
  `);
  await db.execute(sql`DELETE FROM label_prints WHERE cert_id LIKE ${certPat}`);
  await db.execute(sql`DELETE FROM label_overrides WHERE cert_id LIKE ${certPat}`);
  await db.execute(sql`DELETE FROM reprint_log WHERE cert_id LIKE ${certPat}`);
  await db.execute(sql`DELETE FROM ownership_history WHERE cert_id LIKE ${certPat}`);
  await db.execute(sql`DELETE FROM stolen_reports WHERE cert_id LIKE ${certPat}`);
  await db.execute(sql`DELETE FROM certificates WHERE certificate_number LIKE ${certPat}`);
  await db.execute(sql`DELETE FROM customer_magic_link_tokens WHERE email LIKE ${emailPat}`);
  await db.execute(sql`
    DELETE FROM password_reset_tokens
    WHERE user_id IN (SELECT id FROM users WHERE email LIKE ${emailPat})
  `);
  await db.execute(sql`
    DELETE FROM email_verification_tokens
    WHERE user_id IN (SELECT id FROM users WHERE email LIKE ${emailPat})
  `);
  await db.execute(sql`
    DELETE FROM account_magic_link_tokens
    WHERE user_id IN (SELECT id FROM users WHERE email LIKE ${emailPat})
  `);
  await db.execute(sql`DELETE FROM users WHERE email LIKE ${emailPat}`);

  // NOTE: audit_log rows are intentionally NOT deleted — they preserve the
  // immutable record of every seed/reset operation (entity_type='staging_harness').

  return { ok: true, dryRun: false, deleted: counts };
}
