/**
 * Build a Partner submission draft that genuinely satisfies the production submit contract.
 *
 * WHY THIS EXISTS. `submitSubmission` enforces an ordered chain of preconditions, and a fixture that
 * misses an EARLY one can never exercise a LATE one. Three suites each hand-rolled their own draft
 * setup, all of them predating the customer/service/image requirements, and every one of their
 * submit tests was failing on the FIRST gate — so tests whose stated intent was "prove the tier
 * revalidation returns 409" were actually proving "no customer selected returns 400". Some of their
 * follow-on assertions (no handoff written, submission still draft) even PASSED, for entirely the
 * wrong reason.
 *
 * The precondition order in submitSubmission, which this helper exists to satisfy completely:
 *   1. at least one non-removed card
 *   2. customer_id set, and owned by the same tenant
 *   3. service_tier_code set
 *   4. front + back image keys present AND matching
 *      partner-submissions/{tenantId}/{submissionId}/{cardId}/{side}-
 *   5. BOTH objects verifiable in real storage via headR2
 *   6. every card quantity a safe integer >= 1
 *   7. the tier STILL active at submit time  <- the first gate a "tier disabled" test should hit
 *   8. sufficient credits: ONE per physical unit, i.e. SUM(quantity), not row count
 *
 * A test targeting gate N must satisfy 1..N-1, or it proves nothing about N.
 *
 * WHY IT DRIVES THE REAL HTTP ROUTES rather than writing rows and objects directly:
 *   - the image key is generated by production's own cardImageKey, so cardImageKeyAllowed passes BY
 *     CONSTRUCTION and cannot drift if the key format changes. A hand-built key would silently
 *     invalidate the fixture while the test kept "passing";
 *   - uploadCardImage validates real MAGIC BYTES via fileTypeFromBuffer, so the fixture cannot
 *     smuggle in arbitrary bytes;
 *   - the draft-state and tenant-ownership guards on the upload route are exercised too;
 *   - the real card_image_uploaded event and audit rows are written, so a test asserting on the
 *     audit trail is not reading back something the fixture seeded itself.
 * The one thing it cannot do through HTTP is prove the object exists — that is deliberately checked
 * against storage afterwards, because headR2 is a live HEAD and a green upload response is not
 * proof the bytes landed.
 *
 * Customer creation goes through the admin connection rather than the API purely to conserve the
 * per-user mutation-limiter budget (60/min); ownership is still tenant-correct, which is what the
 * submit contract actually checks.
 */
import type { Client } from "pg";
import { ONE_PIXEL_PNG, type PartnerTestStorage } from "./partner-test-storage";

export interface SubmitReadyDraft {
  customerId: string;
  tierCode: string;
  submissionId: string;
  cardIds: string[];
  imageKeys: Record<string, { front: string; back: string }>;
  /** SUM(quantity) — the number of PHYSICAL cards, which is what credits are charged per. */
  expectedPhysicalUnits: number;
  /** One credit per physical unit. Equal to expectedPhysicalUnits by construction. */
  expectedCreditRequirement: number;
}

export interface SubmitReadyOptions {
  /** `fetch`-based JSON helper the suite already has: (method, path, cookie, body?) => {status, body}. */
  j: (method: string, path: string, cookie: string, body?: unknown) => Promise<{ status: number; body: any }>;
  /** Base URL of the running test server, for multipart uploads. */
  base: string;
  cookie: string;
  admin: Client;
  tenantId: string;
  locationId: string;
  storage: PartnerTestStorage;
  tierCode?: string;
  cards?: { cardName: string; quantity?: number }[];
  customerId?: string;
  /** Skip the image step, for a fixture that must fail at gate 4/5 on purpose. */
  withImages?: boolean;
}

/** Upload one side through the REAL multipart route and return the key production generated. */
async function uploadSide(
  base: string,
  cookie: string,
  submissionId: string,
  cardId: string,
  side: "front" | "back"
): Promise<string> {
  const form = new FormData();
  // multer's fileFilter checks the FILENAME extension, and uploadCardImage independently checks the
  // magic bytes. Both have to be satisfied — a .png name with non-PNG bytes is rejected.
  form.append("image", new Blob([new Uint8Array(ONE_PIXEL_PNG)], { type: "image/png" }), `${side}.png`);
  const res = await fetch(`${base}/api/partner/submissions/${submissionId}/cards/${cardId}/images/${side}`, {
    method: "POST",
    headers: { cookie },
    body: form,
  });
  const body = await res.json().catch(() => ({}));
  if (res.status !== 200) {
    throw new Error(`fixture image upload failed (${side}): ${res.status} ${JSON.stringify(body)}`);
  }
  const key = body?.key ?? body?.imageKey ?? body?.[`${side}ImageKey`];
  if (typeof key !== "string" || key.length === 0) {
    throw new Error(`fixture image upload returned no key for ${side}: ${JSON.stringify(body)}`);
  }
  return key;
}

export async function createSubmitReadyPartnerDraft(opts: SubmitReadyOptions): Promise<SubmitReadyDraft> {
  const {
    j,
    base,
    cookie,
    admin,
    tenantId,
    locationId,
    storage,
    tierCode = "standard",
    cards = [{ cardName: "Fixture Charizard" }],
    withImages = true,
  } = opts;

  // A tenant-owned customer. verifyCustomerOwnership re-checks tenant_id in the application, because
  // the FK alone bypasses RLS — so a customer from another tenant is rejected even though it exists.
  let customerId = opts.customerId;
  if (!customerId) {
    const { rows } = await admin.query<{ id: string }>(
      "INSERT INTO partner_customers (tenant_id, full_name) VALUES ($1, $2) RETURNING id",
      [tenantId, `Fixture Customer ${Date.now()}-${Math.round(performance.now())}`]
    );
    customerId = rows[0].id;
  }

  /**
   * customerId and serviceTierCode go in the CREATE body, not a follow-up PATCH.
   * `version` is load-bearing: a PATCH would bump partner_submissions.version to 2, and callers that
   * later PATCH with an explicit version (the tier-disabled test does) would then send a stale one.
   * Creating with both fields leaves version at 1, which is what a freshly-created draft has in
   * production too.
   */
  const created = await j("POST", "/api/partner/submissions", cookie, {
    locationId,
    customerId,
    serviceTierCode: tierCode,
  });
  if (created.status !== 201) {
    throw new Error(`fixture draft creation failed: ${created.status} ${JSON.stringify(created.body)}`);
  }
  const submissionId: string = created.body.id;

  const cardIds: string[] = [];
  const imageKeys: Record<string, { front: string; back: string }> = {};
  let expectedPhysicalUnits = 0;

  for (const card of cards) {
    const quantity = card.quantity ?? 1;
    const res = await j("POST", `/api/partner/submissions/${submissionId}/cards`, cookie, {
      cardName: card.cardName,
      ...(card.quantity === undefined ? {} : { quantity }),
    });
    if (res.status !== 201 && res.status !== 200) {
      throw new Error(`fixture card creation failed: ${res.status} ${JSON.stringify(res.body)}`);
    }
    const cardId: string = res.body.id ?? res.body.card?.id;
    if (!cardId) throw new Error(`fixture card creation returned no id: ${JSON.stringify(res.body)}`);
    cardIds.push(cardId);
    // Credits are charged per PHYSICAL card: a row with quantity 3 is 3 units, not 1.
    expectedPhysicalUnits += quantity;

    if (withImages) {
      const front = await uploadSide(base, cookie, submissionId, cardId, "front");
      const back = await uploadSide(base, cookie, submissionId, cardId, "back");
      imageKeys[cardId] = { front, back };
      // Production generates these keys (partner-submissions/...), not the helper, so they are not
      // under the run prefix and must be registered explicitly or cleanup will silently skip them.
      storage.track(front);
      storage.track(back);

      // A 200 from the upload route is not proof the bytes reached storage, and headR2 at submit
      // time is a live HEAD. Verify here so a storage misconfiguration surfaces as an explicit
      // fixture error rather than as a confusing "images could not be verified" 400 from submit.
      for (const key of [front, back]) {
        if (!(await storage.exists(key))) {
          throw new Error(`fixture uploaded ${key} but it is not present in storage — check R2_* wiring`);
        }
      }
    }
  }

  return {
    customerId,
    tierCode,
    submissionId,
    cardIds,
    imageKeys,
    expectedPhysicalUnits,
    expectedCreditRequirement: expectedPhysicalUnits,
  };
}
