/**
 * Point the application's R2 client at a DISPOSABLE local/CI MinIO, safely.
 *
 * The Partner submit contract verifies every card image with a live `headR2` (submission-service.ts
 * ~L920), so a suite that submits cannot fake storage — it needs real objects in a real bucket. This
 * helper is how the three HTTP suites get one without ever being able to reach real storage.
 *
 * WHY A SEPARATE BUCKET FROM THE PROOF SUITE. tests/partner-real-r2-storage.test.ts refuses to run
 * if its bucket contains ANY object outside `ci-proof/`, and the submit path writes keys under
 * `partner-submissions/...`. Pointing the fixtures at `partner-real-r2-proof` would therefore make
 * the storage proof abort — correctly — the moment a fixture ran first. The fixtures get their own
 * bucket, which the proof suite's own name pattern already anticipates.
 *
 * WHY THIS READS PARTNER_REAL_R2_PROOF_* AND NEVER R2_*. It writes process.env.R2_* for the app to
 * consume, but it never READS them. An earlier revision of the proof suite resolved its endpoint
 * from R2_ENDPOINT with localhost merely as a fallback, then ran an unprefixed list -> bulk delete
 * -> DeleteBucket in beforeAll. With real credentials present that would have destroyed live
 * customer objects and then the production bucket. Deriving only from the dedicated proof variables
 * means an ambient production configuration cannot become the target, whatever else is exported.
 *
 * The guards below are the same shape as ensure-proof-bucket.mjs: an EXACT hostname allow-list
 * (substring checks pass "https://evil.example/?h=127.0.0.1"), an independent forbidden-host check
 * so widening the allow-list is not by itself enough to reach production, and a disposable
 * bucket-name pattern. Cleanup is per-object under a unique per-run prefix; there is no
 * DeleteBucket and no unprefixed delete anywhere in this file, by design.
 */
import { randomUUID } from "node:crypto";
import {
  S3Client,
  PutObjectCommand,
  HeadObjectCommand,
  ListObjectsV2Command,
  DeleteObjectCommand,
  CreateBucketCommand,
} from "@aws-sdk/client-s3";

const ALLOWED_STORAGE_HOSTS = new Set(["127.0.0.1", "localhost", "::1", "minio"]);
const FORBIDDEN_HOST_FRAGMENTS = ["r2.cloudflarestorage.com", "amazonaws.com", "backblazeb2.com"];
/** Deliberately narrow: only a disposable fixtures bucket, never a bare production-looking name. */
const FIXTURE_BUCKET_RE = /^partner-real-r2-proof-[a-z0-9]{1,16}$/;

export interface PartnerTestStorage {
  bucket: string;
  endpoint: string;
  /** Unique to this process+run. Used for objects THIS helper writes directly. */
  runPrefix: string;
  client: S3Client;
  /**
   * Register a key the fixture caused to be created, so cleanup can remove it.
   *
   * Necessary because the interesting keys are generated by PRODUCTION (cardImageKey ->
   * partner-submissions/{tenant}/{submission}/{card}/{side}-...), not by this helper, so they do
   * NOT live under runPrefix. An earlier version cleaned by prefix alone and therefore deleted
   * nothing: a local run left 62 orphaned objects behind, which in CI would grow every build.
   */
  track(key: string): void;
  /** Delete exactly the objects this run created — tracked keys plus anything under runPrefix. */
  cleanup(): Promise<void>;
  /** True when the object exists — used to prove an upload really landed. */
  exists(key: string): Promise<boolean>;
  /** Write bytes at an exact key (for fixtures that cannot go through the HTTP upload route). */
  put(key: string, body: Buffer, contentType?: string): Promise<void>;
  /**
   * Delete ONE object, so a test can prove storage verification is actually ENFORCED.
   *
   * Without this, a suite that always uploads real objects cannot tell "headR2 is checked" from
   * "headR2 was deleted from the code" — verified: removing the headR2 call from submitSubmission
   * left the mount suite fully green. Proving the gate needs an object that is genuinely absent.
   */
  remove(key: string): Promise<void>;
}

/** Is a disposable local MinIO configured for this run? Suites use this to fail closed in CI. */
export function partnerTestStorageConfigured(): boolean {
  return Boolean(
    process.env.PARTNER_REAL_R2_PROOF_ENDPOINT &&
      process.env.PARTNER_REAL_R2_PROOF_KEY &&
      process.env.PARTNER_REAL_R2_PROOF_SECRET
  );
}

/**
 * Configure process.env.R2_* for the application under test and return a handle.
 *
 * MUST be called BEFORE the first import of anything that pulls in server/r2.ts: that module
 * memoises its S3 client at module scope, so the first getR2Client() wins for the whole file.
 */
export async function setupPartnerTestStorage(opts: { bucketSuffix: string }): Promise<PartnerTestStorage> {
  const endpoint = process.env.PARTNER_REAL_R2_PROOF_ENDPOINT;
  const accessKeyId = process.env.PARTNER_REAL_R2_PROOF_KEY;
  const secretAccessKey = process.env.PARTNER_REAL_R2_PROOF_SECRET;
  if (!endpoint || !accessKeyId || !secretAccessKey) {
    throw new Error(
      "PARTNER_REAL_R2_PROOF_ENDPOINT / _KEY / _SECRET must be set for a suite that needs real storage. " +
        "Do NOT substitute R2_* — the dedicated names exist so an ambient production configuration " +
        "can never become the target."
    );
  }

  let host: string;
  try {
    const url = new URL(endpoint);
    if (url.protocol !== "http:" && url.protocol !== "https:") {
      throw new Error(`refusing storage endpoint protocol ${url.protocol}`);
    }
    host = url.hostname.replace(/^\[|\]$/g, "");
  } catch (err) {
    throw new Error(`PARTNER_REAL_R2_PROOF_ENDPOINT is not a usable URL: ${(err as Error).message}`);
  }
  for (const bad of FORBIDDEN_HOST_FRAGMENTS) {
    if (host.includes(bad)) throw new Error(`refusing to run fixtures against real storage host ${host}`);
  }
  if (!ALLOWED_STORAGE_HOSTS.has(host)) {
    throw new Error(`storage host ${host} is not allow-listed for test fixtures`);
  }

  const bucket = `${process.env.PARTNER_REAL_R2_PROOF_BUCKET ?? "partner-real-r2-proof"}-${opts.bucketSuffix}`;
  if (!FIXTURE_BUCKET_RE.test(bucket)) {
    throw new Error(`refusing fixture bucket "${bucket}": not a disposable fixtures bucket name`);
  }

  const client = new S3Client({
    region: "auto",
    endpoint,
    forcePathStyle: true,
    credentials: { accessKeyId, secretAccessKey },
    requestChecksumCalculation: "WHEN_REQUIRED",
    responseChecksumValidation: "WHEN_REQUIRED",
  });

  try {
    await client.send(new CreateBucketCommand({ Bucket: bucket }));
  } catch (err) {
    const name = (err as { name?: string }).name ?? "";
    if (name !== "BucketAlreadyOwnedByYou" && name !== "BucketAlreadyExists") throw err;
  }

  // The application reads these. forcePathStyle is required for MinIO.
  process.env.R2_ENDPOINT = endpoint;
  process.env.R2_ACCESS_KEY_ID = accessKeyId;
  process.env.R2_SECRET_ACCESS_KEY = secretAccessKey;
  process.env.R2_BUCKET_NAME = bucket;
  process.env.R2_FORCE_PATH_STYLE = "1";

  const runPrefix = `fixtures/${process.env.GITHUB_RUN_ID ?? "local"}-${process.pid}-${randomUUID()}/`;
  const tracked = new Set<string>();

  return {
    bucket,
    endpoint,
    runPrefix,
    client,
    async exists(key: string) {
      try {
        await client.send(new HeadObjectCommand({ Bucket: bucket, Key: key }));
        return true;
      } catch {
        return false;
      }
    },
    track(key: string) {
      tracked.add(key);
    },
    async remove(key: string) {
      await client.send(new DeleteObjectCommand({ Bucket: bucket, Key: key }));
      tracked.delete(key);
    },
    async put(key: string, body: Buffer, contentType = "image/png") {
      tracked.add(key);
      await client.send(new PutObjectCommand({ Bucket: bucket, Key: key, Body: body, ContentType: contentType }));
    },
    async cleanup() {
      /**
       * Deletes ONLY what this run created: every explicitly tracked key, then anything under
       * runPrefix. One DeleteObject per key — never a bulk DeleteObjects, never DeleteBucket, and
       * never an unprefixed list-and-delete. A bug here can therefore destroy at most this run's
       * own objects, which is the property that matters after an earlier revision of the storage
       * proof suite listed and bulk-deleted a whole bucket in beforeAll.
       */
      for (const key of tracked) {
        await client.send(new DeleteObjectCommand({ Bucket: bucket, Key: key })).catch(() => {});
      }
      tracked.clear();

      let token: string | undefined;
      do {
        const page: Awaited<ReturnType<typeof client.send>> = await client.send(
          new ListObjectsV2Command({ Bucket: bucket, Prefix: runPrefix, ContinuationToken: token })
        );
        const listed = page as { Contents?: { Key?: string }[]; NextContinuationToken?: string; IsTruncated?: boolean };
        for (const obj of listed.Contents ?? []) {
          const key = obj.Key ?? "";
          if (!key.startsWith(runPrefix)) continue; // belt and braces
          await client.send(new DeleteObjectCommand({ Bucket: bucket, Key: key }));
        }
        token = listed.IsTruncated ? listed.NextContinuationToken : undefined;
      } while (token);
    },
  };
}

/**
 * A real 1x1 PNG.
 *
 * uploadCardImage runs fileTypeFromBuffer and rejects anything whose MAGIC BYTES are not
 * JPEG/PNG/WebP/TIFF, regardless of the declared content type — so a fixture cannot hand it
 * arbitrary bytes with a nice filename. These are genuine PNG bytes.
 */
export const ONE_PIXEL_PNG = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==",
  "base64"
);
